### ISSUE TITLE
Custom Event Attribute bind handlers at render time

### ISSUE THREAD

**Issue by LucaColonnello** [mojo-js/paperclip.js#274] opened 2015-07-15 10:13 UTC
Hi,
I used the method suggested in the issue #272.
Here's my jsBin: http://jsbin.com/rupilasibi/3/edit?html,js,output

My goal is to have a tap event, or something else with hammer.js.
I've tryed with click only for example.

The problem is that the click handle is called at render time and the initialize function in the attribute is never called.

There's a way to make this stuff work?

Thank you in advice.

**Comment by LucaColonnello** [comment] 2015-07-17 13:59
Nothing here?

**Comment by crcn** [comment] 2015-07-17 18:00
Figured out what the issue is (and it's a bug). Right now custom components need to be registered with a key that's all lower case. So instead of writing this:

```javascript
pc.template("<div onCustomClick={{handle()}}></div>", {
  onCustomClick: CustomAttribute
});
```

You'll need to write:

```javascript
pc.template("<div onCustomClick={{handle()}}></div>", {
  oncustomclick: CustomAttribute
});
```
I've filed a ticket for [this issue](https://github.com/mojo-js/paperclip.js/issues/277), and it should be fixed in the next few releases.

**Comment by LucaColonnello** [comment] 2015-07-17 18:40
Ok, I've update my JSBIN example:
http://jsbin.com/newulenoke/1/edit?html,js,output

But I don't understand why:

- the Custom Click Handler is called at first time render
- I have to pass the handler to the template function

The default onClick event requires only the handler into the object passed to the `.view( )` function, and also it isn't called at first time render...

Have you every explaination of this?

**Comment by crcn** [comment] 2015-07-17 18:58
Fixed: http://jsbin.com/newulenoke/1/edit?html,js,output

the `paperclip.Attribute` class executes the `value` script immediately after it's bound to a context. Simple fix for this is to override the `bind` method with an empty function. `v3` will not require you to do this.

**Comment by LucaColonnello** [comment] 2015-07-17 19:01
Ok fixed: http://jsbin.com/safoyireco/1/edit?html,js,output
`v3` will not require we pass the handler on the template function too?

**Comment by crcn** [comment] 2015-07-17 19:41
The current version of paperclip doesn't require you to pass custom event handlers in the template function, but it's the preferred way since it keeps custom attribute handlers and components out of the global scope. 

You can register custom attribute handlers by assigning it to the default attribute handlers property, like so:

```javascript
paperclip.attributes.oncustomclick = CustomClickHandler;
```

This approach allows you to define `onCustomClick` in any template without needing to register it to each template. Like so:

```javascript
var tpl = pc.template("<div onCustomClick={{handle()}} />");
```

**Comment by LucaColonnello** [comment] 2015-07-17 19:48
Ok, sorry this is not the question...
I notice that if I remove the handler in the template function, it works with the handler into the object passed to the view function as well.

Ok, I hope this library will be improved. I'm using it in a big project for small views and it is perfect for web sites development..

**Comment by crcn** [comment] 2015-07-20 17:24
Hmm, still don't understand what the issue is. Do you have an example or pseudocode of what you'd like changed?

**Comment by LucaColonnello** [comment] 2015-07-20 17:49
No, mine is only a consideration.
By now, your answers was great and helpful!

Thank you

Il lunedì 20 luglio 2015, Craig Condon <notifications@github.com> ha
scritto:

> Hmm, still don't understand what the issue is. Do you have an example or
> pseudocode of what you'd like changed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojo-js/paperclip.js/issues/274#issuecomment-122960086>
> .
>


-- 
Luca Colonnello
+39 345 8948718
luca.colonnello91@gmail.com

**Comment by crcn** [comment] 2015-07-20 18:15
Awesome. Definitely reach out if you have anymore feedback, or you'd like to see anything implemented in the library!

**Closed** 2015-07-20 18:14 UTC
